apiversion /; app/v1
kind : Deployment
metadata :
  app:myapp
  spec:
  replica:1
  selectors;
  matchlabesl:
  app:myapp
  template:
  metadata:
  labels:
  app:myapp
spec:
containsers:
-name:myapp
image:myapp:latest
port:
-containerport:5000